export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_SORTED_MOVIES = 'FETCH_SORTED_MOVIES';
export const FETCH_FILTERED_MOVIES = 'FETCH_FILTERED_MOVIES';
export const FETCH_SEARCHED_MOVIES = 'FETCH_SEARCHED_MOVIES';
