export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SET_FILTER_GENRE = 'SET_FILTER_GENRE';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_SEARCHED_MOVIES = 'SET_SEARCHED_MOVIES';
export const DELETE_MOVIES = 'DELETE_MOVIES';
